name = "mistllc.org"
main = "./worker/index.ts"
compatibility_date = "2025-08-14"
compatibility_flags = [ "nodejs_compat" ]


[vars]
VITE_API_BASE = "https://mistllc-backend.jacobnixon59.workers.dev"

[[kv_namespaces]]
binding = "MISTLLC_KV"
id = "2d250836cc7d4adebb9d6a5968671077"

[placement]
mode = "smart"

[assets]
directory = "./dist/client/"
binding = "ASSETS"