name = "mistllc-backend-worker"
main = "./backend/dist/index.ts"
compatibility_date = "2025-08-03"
compatibility_flags = [ "nodejs_compat" ]
account_id = "55221ae8c513e4288ff1986ad16ae04d"


[vars]
VITE_API_BASE = "https://mistllc-backend-worker.jacobnixon59.workers.dev"

[KV namespace]
binding = "mistllc"
id = "<KV_NAMESPACES_ID>"

[placement]
mode = "smart"

