version: "3.9"

services:
  backend:
    image: node:20-alpine
    container_name: mistllc-backend-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    command: sh -c "npm install && npm run dev"
