name = "mistllc-backend-worker"
main = "dist/index.js"
account_id = "55221ae8c513e4288ff1986ad16ae04d"
workers_dev = true
compatibility_date = "2025-08-12"

[vars]
DATABASE_URL = "https://mistllc-backend-worker.jacobnixon59.workers.dev"
API_KEY = "http://127.0.0.1:8787/api/hello"


[env.production]
route = "https://mistllc-backend-worker.jacobnixon59.workers.dev"
zone_id = "dddda5a67e3dea16e0469c7215f08e2b"

[[kv_namespaces]]
binding = "mistllc"
id = "2d250836cc7d4adebb9d6a5968671077"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true



