name = "mistllc-backend-worker"
main = "dist/src/index.js"
compatibility_date = "2025-08-18"

# KV binding for persistence
[[kv_namespaces]]
binding = "mistllc"
id = "2d250836cc7d4adebb9d6a5968671077"    

