name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: |
            backend/node_modules
            frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Build backend (if needed, e.g. tsc)
        working-directory: ./backend
        run: npm run build || echo "No build script, skipping"

      - name: Run tests (optional)
        # Add your test commands here
        run: echo "Add your tests here"

      # Optional: Docker build & push steps if you want container deployment
      # Optional: Deploy steps (to cloud, server, etc.)

