permissions: {}
name: "Dependabot Workflow Example"

on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Show message
        run: echo "This is a placeholder workflow. Dependabot configuration should be in .github/dependabot.yml, not as a workflow."
