version: 2
updates:
  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
    rebase-strategy: "auto"

  # npm in root
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
    rebase-strategy: "auto"

  # Optional: npm in frontend/
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
      time: "01:00"
    open-pull-requests-limit: 5

  # Dockerfile in root
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"

  # pip (Python) dependencies in root
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"

  # Java (Gradle) dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
