name: Deploy Fullstack App

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Install dependencies
      - name: Install frontend dependencies
        run: npm install --prefix frontend

      - name: Install backend dependencies
        run: npm install --prefix backend

      # Build steps
      - name: Build Frontend
        run: npm run build --prefix frontend

      - name: Build Backend
        run: npm run build --prefix backend

      # Docker publishing
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Frontend Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/mistllc-frontend:latest ./frontend
          docker push ghcr.io/${{ github.repository_owner }}/mistllc-frontend:latest

      - name: Build and Push Backend Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/mistllc-backend:latest ./backend
          docker push ghcr.io/${{ github.repository_owner }}/mistllc-backend:latest
