name: Deploy Fullstack App

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Frontend
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/mistllc-frontend:latest ./frontend
          docker push ghcr.io/${{ github.repository_owner }}/mistllc-frontend:latest

      - name: Build and Push Backend
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/mistllc-backend:latest ./backend
          docker push ghcr.io/${{ github.repository_owner }}/mistllc-backend:latest
