name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean install --file pom.xml

      - name: Run tests
        run: mvn test

      # Optional: Upload dependency graph to GitHub for better Dependabot support
      - name: Submit dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4
